version: '3'

services:
  database:
    image: mongo:latest
    ports:
      - "27017:27017"

  server:
    image: gaor/drop-table-overview:latest
    depends_on:
      - 'database'
    ports: 
      - '8008:8008'
    environment:
      WAIT_HOSTS: database:27017

