version: 2
jobs:
  build:
    working_directory: ~/circleci_deployment
    docker:
      - image: circleci/node:10.7.0-stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: server
          command: npm run server-dev
      - run:
          name: test
          command: npm run test
      - run:
          name: coverage
          command: npm run send-coverage